{- |
Module      : Main
Description : Gnosis - The Stateful Artefacts Rendering Engine
Copyright   : (c) 2025-2026 Jonathan D.A. Jewell
License     : AGPL-3.0-or-later
Maintainer  : hyperpolymath

Gnosis reads Guile Scheme metadata (STATE.scm) and renders template
documents into static output suitable for Git forges.

Usage: gnosis <template> <output>
Example: gnosis AI.template.djot AI.djot
-}

module Main (main) where

import System.Environment (getArgs)
import System.IO (readFile, writeFile)
import System.Directory (doesFileExist)
import qualified Data.Map.Strict as Map

import Types (FlexiText(..), Context)
import SExp (parseSExp, findInTree)
import Render (renderWithBadges)
import SixSCM (loadAll6SCM, defaultSCMPath)
import Paxos (getCurrentTimestamp)

-- | Load project state from STATE.scm and build the rendering context.
loadState :: FilePath -> IO Context
loadState path = do
    exists <- doesFileExist path
    if not exists
        then do
            putStrLn $ "Warning: " ++ path ++ " not found. Using defaults."
            return defaultContext
        else do
            content <- readFile path
            case parseSExp content of
                Nothing -> do
                    putStrLn "Error: Could not parse STATE.scm"
                    return defaultContext
                Just tree -> do
                    let mood = findInTree "mood" tree
                    let version = findInTree "version" tree
                    let phase = findInTree "phase" tree
                    let compliance = findInTree "compliance-level" tree
                    let health = findInTree "health-score" tree
                    return $ Map.fromList
                        [ ("mood", FlexiText (maybe "unknown" id mood)
                                             ("Current mood: " ++ maybe "unknown" id mood))
                        , ("version", FlexiText (maybe "0.0.0" id version)
                                                ("Version " ++ maybe "0.0.0" id version))
                        , ("phase", FlexiText (maybe "unknown" id phase)
                                              ("Phase: " ++ maybe "unknown" id phase))
                        , ("compliance", FlexiText (maybe "?" id compliance)
                                                   ("Compliance level: " ++ maybe "?" id compliance))
                        , ("health", FlexiText (maybe "?" id health)
                                               ("Health score: " ++ maybe "?" id health))
                        , ("engine", FlexiText "Gnosis"
                                               "Engine: Gnosis (Haskell)")
                        , ("generator", FlexiText "Gnosis/Haskell"
                                                  "Generated by Gnosis Haskell engine")
                        ]

-- | Default context when STATE.scm is unavailable.
defaultContext :: Context
defaultContext = Map.fromList
    [ ("mood", FlexiText "unknown" "Status unknown - STATE.scm not found")
    , ("version", FlexiText "0.0.0" "Version unknown")
    , ("phase", FlexiText "unknown" "Phase unknown")
    , ("compliance", FlexiText "?" "Compliance unknown")
    , ("health", FlexiText "?" "Health unknown")
    , ("engine", FlexiText "Gnosis" "Engine: Gnosis (Haskell)")
    , ("generator", FlexiText "Gnosis/Haskell" "Generated by Gnosis")
    ]

-- | Main entry point.
main :: IO ()
main = do
    args <- getArgs
    case args of
        [templatePath, outputPath] -> do
            putStrLn "Gnosis: Stateful Artefacts Engine v1.0.0"
            putStrLn $ "  Template: " ++ templatePath
            putStrLn $ "  Output:   " ++ outputPath

            -- Load all 6scm files from .machine_readable/
            ctx <- loadAll6SCM "../.machine_readable"

            -- Read template
            templateExists <- doesFileExist templatePath
            if not templateExists
                then putStrLn $ "Error: Template not found: " ++ templatePath
                else do
                    template <- readFile templatePath
                    let result = renderWithBadges ctx template
                    writeFile outputPath result
                    putStrLn "Hydration complete."

        ["--version"] ->
            putStrLn "Gnosis v1.0.0 - Git Forge Complete (6scm + Paxos-Lite + DAX)"

        ["--help"] -> do
            putStrLn "Gnosis - The Stateful Artefacts Rendering Engine"
            putStrLn ""
            putStrLn "Usage: gnosis <template> <output>"
            putStrLn "       gnosis --version"
            putStrLn "       gnosis --help"
            putStrLn ""
            putStrLn "Gnosis reads STATE.scm and renders template placeholders"
            putStrLn "into static, accessible documentation."

        _ -> do
            putStrLn "Usage: gnosis <template.djot> <output.djot>"
            putStrLn "       gnosis --help for more information"
